- hosts: azure
  become: true

  tasks:
    - name: Error handling
      block:
        - name: Print a message
          debug:
            msg: 'I execute normally'

        - name: Force a failure
          command: /bin/false
      rescue:
        - name: Successful command
          command: ls -al /opt
      always:
        - name: Always do this
          debug:
            msg: "This always executes"