- name: Install firewalld
  package:
    name: "firewalld"
    state: present

- name: Start firewalld 
  service:
    name: firewalld
    state: started

- name: Open port 
  firewalld:
    port: "{{ port }}/tcp"
    state: enabled
    permanent: true
    immediate: true

- name: Install apache
  package:
    name: "{{ package }}"
    state: present
  notify: Restart Apache
