- hosts: localhost

  tasks:
    - name: Get facts of the VM's ssh public key by resource group
      azure.azcollection.azure_rm_sshpublickey_info:
        ad_user: student_7pmnzk18m7b1ghfx_003944345@vocareumvocareum.onmicrosoft.com
        password: f75!V#2c%GQ
        resource_group: Regroup_6iNbgkWS
        subscription_id: 94ec3a64-dcfe-4219-9e29-88221690c382
      register: azure_keys
    
    - name: Show Azure Keys
      debug:
        msg: "{{ azure_keys }}"