- hosts: azure
  become: true

  tasks:
    - name: List contents of 2 directories
      shell: ls "{{ item }}"
      loop:
       - "/etc"
       - "/var"
    
    - name: Uname -r
      shell: uname -r
      when:
        - ansible_facts['distribution'] == "Debian"
        - ansible_facts['distribution_major_version'] == "24"

    - name: Stat folder
      stat:
        path: "{{ folder }}"